version: '3.4'

services:
  redis-server:
    image: 'redis'
    
  grpcnodeserver:
    image: grpcnodeserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
